version: "3"

services:
  react:
    build: .
    container_name: my-app
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_ssl
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - react_app:/usr/share/nginx/html:ro
    ports:
      - "8082:80" # Замінили порт 80 на 8080
      - "8443:443" # Порт 443 залишаємо на 8443
    depends_on:
      - react

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c"
    command: >
      "sleep 10 &&
      certbot certonly --webroot --webroot-path=/var/www/certbot
      -d win-partners.duckdns.org
      --email your@email.com --agree-tos --no-eff-email --force-renewal"

volumes:
  react_app:
