version: "3.7"

services:
  certbot:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'while :; do certbot renew --webroot -w /var/www/certbot --email zhomyruk.yaroslav.v@gmail.com -d win-partners.duckdns.org --agree-tos --force-renewal --rsa-key-size 2048 --non-interactive && sleep 12h; done'"

  nginx:
    image: nginx:alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./frontend_win/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend_win/build:/usr/share/nginx/html
    ports:
      - "8082:80" # Відкриваємо порт 8082 на хості і мапимо його на порт 80 в контейнері
      - "8444:443" # Відкриваємо порт 8444 на хості і мапимо його на порт 443 в контейнері
    depends_on:
      - certbot # Очікуємо на сертифікат від Certbot

  frontend_win:
    build:
      context: ./frontend_win
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80" # Якщо ви хочете напряму відкрити порт для dev-сервера (для тестування)
    depends_on:
      - certbot # Очікуємо на сертифікат від Certbot
